import res_config
import sale
import partner
import country
import packs
import product
import product_group
import website_sale
import import_data
import pricelist
import offers
import website_crm
import cs_tools
import ir_attachment
import marketing
import ir_cron
